### ISSUE TITLE
Chain Density - Feature Request

### ISSUE THREAD

**Issue by CyberCyclone** [CardanoSolutions/ogmios#112]
#### Describe your idea, in simple words.
Add chain density to endpoint 'health' -> lastKnownTip or wherever it's most appropriate.

#### Why is it a good idea?
It's a good metric to determine the health of the blockchain in real time.

#### Are you willing to work on it yourself?
Unfortunately not. I'm not familiar enough to know where it comes from in cardano-node.

**Comment by KtorZ** [comment]
If I recall correctly, the chain density is calculated on the fly by cardano-node as the ratio of the number of blocks over the number of slots for a certain period of time, typically `k` blocks in the past. 

This is done in an ad-hoc way and not provided by the node in any of the API. This _could_ be implemented in Ogmios, although the server does not persist any past data, and has no direct access to cardano-node's database which means that it cannot look in the past for running the calculation and; it would have to be done at runtime and would only converge towards the value reported by the node after ~30 minutes of uptime (k slots) (after what, it's a rolling metric). 

I wonder though if it's not already possible to get that metric from the node itself, via the EKG or Prometheus port which are sending out some metrics already :thinking:

**Comment by CyberCyclone** [comment]
Based on your response, it sounds like it would need to "warm up" to start to gather enough blocks to make an accurate calculation. It sounds like a lot more effort then I thought seeing as it's not part of the cardano-node api.

I'm currently doing it through cardano-graphql, which is pretty easy so I've got a working solution. Just thought it would be useful to pull from an official Cardano tool as it's an often used metric.
 
```
let rawResult = HTTP.call("POST", GRAPHQL_ADDRESS, {
		data: {"query": `{blocks_aggregate( where:{forgedAt: {_gte: "${moment().subtract(10, 'minutes').format()}", _lt: "${moment().subtract(20, 'seconds').format()}" }}) {aggregate{count}}}`}
	});
let totalSlots = 580;	// Slots = 60 seconds * 10 - 20 seconds = 10 minutes (minus 20 seconds) of slots expected
let count = JSON.parse(rawResult.content).data.blocks_aggregate.aggregate.count;
let density = count / totalSlots;
return density*100; // Percentage
```

**Comment by KtorZ** [comment]
An alternative could be to the query to the state query protocol itself, doing a PR to input-output-hk/ouroboros-network so that it's readily available for clients. It is probably less work and less cumbersome to do go that path.

Yet, doing it for a single metric is perhaps a bit excessive and I'd argue that such efforts should expose more metrics to be justified.
