### ISSUE TITLE
Optional flag on QueryResponse[poolIds] and QueryResponse[poolParameters]

### ISSUE THREAD

**Issue by MarcelKlammer** [CardanoSolutions/ogmios#118]
Please remove the ? on 

https://github.com/CardanoSolutions/ogmios/blob/162cbf2ebd498890700aaeff078462a4de332616/clients/TypeScript/packages/schema/src/index.ts#L579

and

https://github.com/CardanoSolutions/ogmios/blob/162cbf2ebd498890700aaeff078462a4de332616/clients/TypeScript/packages/schema/src/index.ts#L592

they lead to errors using the TypeScript compiler.

**Comment by KtorZ** [comment]
Thanks for the catch :ok_hand:
