### ISSUE TITLE
delegationsAndRewards query does not seem to function for me.

### ISSUE THREAD

**Issue by thomasgbereczky** [CardanoSolutions/ogmios#122]
Dear Ogmios,

First I got the stake address's hash 

echo stake1uxmjwsd0d0wyqfm3lk668gur42gk7rhneklhdctwd26qgfq66zfu3 | ./bech32
e1b72741af6bdc402771fdb5a3a383aa916f0ef3cdbf76e16e6ab40424

and then I made this query  -->
{ 
    "type": "jsonwsp/request",
    "version": "1.0",
    "servicename": "ogmios",
    "methodname": "Query",
    "args": { "query": { "delegationsAndRewards": ["e1b72741af6bdc402771fdb5a3a383aa916f0ef3cdbf76e16e6ab40424"] } }
}

It does not seem to work for me, what am I doing wrong?

**Comment by KtorZ** [comment]
`stake1uxmjwsd0d0wyqfm3lk668gur42gk7rhneklhdctwd26qgfq66zfu3` likely refers to a stake address, which is made of:

- a 1 byte header 
- a 28-byte payload which corresponds to a hash of a stake credential (address or script). 

The current API from Ogmios expects an a key hash here, so only the last 28-byte of the stake address (or, last 56 characters when base16-encoded). So try out with: `"b72741af6bdc402771fdb5a3a383aa916f0ef3cdbf76e16e6ab40424"` only (dropping the `e1` prefix which is the header byte). 

Arguably, the API _could_ also accept stake address. I realize this may facilitate interop with other tools better :thinking:

**Comment by thomasgbereczky** [comment]
Seems like it does not work with that either -->

{ 
    "type": "jsonwsp/request",
    "version": "1.0",
    "servicename": "ogmios",
    "methodname": "Query",
    "args": { "query": { "delegationsAndRewards": ["b72741af6bdc402771fdb5a3a383aa916f0ef3cdbf76e16e6ab4042"] } }
}

{"type":"jsonwsp/fault","version":"1.0","servicename":"ogmios","fault":{"code":"client","string":"Invalid request: invalid query."},"reflection":null}

**Comment by KtorZ** [comment]
What version are you running?

**Comment by KtorZ** [comment]
Also, your hash is only 55 bytes long. It's missing a `4` at the end according to your previous message.

**Comment by thomasgbereczky** [comment]
Thanks it works now!
