### ISSUE TITLE
Improve hash type names

### ISSUE THREAD

**Issue by mkazlauskas** [CardanoSolutions/ogmios#139]
#### Describe your idea, in simple words.

`Hash16` and `Hash64` refers to encoding, as in base16 and base64. These type names are confusing, because they imply that they're hash types and not encoding types. I suggest creating more specific types, such as `Hash[byte]ByteBase[base]`, e.g. `Hash28ByteBase16`. Alternatively, it could be something like `Hash[algorithm]Base[base]`.

#### Why is it a good idea?

Users will know exactly what to expect

#### Are you willing to work on it yourself?

Possibly

**Comment by KtorZ** [comment]
That sounds like a nice idea. I am actually pretty unsatisfied with this Hash16 Hash64 myself :grimacing: and for a while, I wanted to replace this with more meaningful aliases which would give information about _what_ is being hashed as well. So perhaps, finding a notation which can carry all of:

- The hash algorithm used
- The length of the digest
- The subject hashed
- The transport encoding

**Comment by mkazlauskas** [comment]
> information about what is being hashed as well

That would be great! 

> The hash algorithm used
The length of the digest
The subject hashed
The transport encoding

I think the length could be omitted if it includes algorithm+subject+encoding

**Comment by KtorZ** [comment]
I am currently looking into this. There are currently 

- 70 occurrences of `Hash16`
- 21 occurrences of `Hash64` 

Not all of them refer to different or same entities. So it'll have to be  a case-by-case change :partying_face: ...
