### ISSUE TITLE
Official prebuilt binaries

### ISSUE THREAD

**Issue by kayandra** [CardanoSolutions/ogmios#140]
Hi there KtorZ and team, thanks for creating ogmios. 

I wanted to ask if it's at all possible to have official prebuilt binaries of ogmios. That way instead of having to build from source (which I haven't been able to do yet) or running docker, we can just have a binary we can dump into our bin folders and have direct access to ogmios CLI.

I checked the previous issues and noticed there's been talk of this. So I wanted to ask if there's any progress on it. Or if I could get better directions for building from source I could contribute to the repo and have it added to workflow.

**Comment by KtorZ** [comment]
Hey @kayandra , that is something I've been after for a while. The problem so far is that building static binaries in Haskell is non-trivial. Even with Nix and Haskell.nix. I tried to have a go at it a while ago without much success. I could try again to see what I can do. Until then, the closest thing we have to a drop-in binary is containers with Docker. Images are pre-built on every push and releases. So, you can in principle get started with just a `docker pull cardanosolutions/ogmios`.

**Comment by kayandra** [comment]
Understood, thanks for the info.

**Comment by KtorZ** [comment]
Fixed in:

- 2e18336ca023d1f9ed8ae9281259668bf0d22d95
- a3c7b461257714782425a0ad5cd815ebf9303ec7
- 3890a065b01639a7189cbb22ec17c3212e99485f

The [Nix workflow](https://github.com/CardanoSolutions/ogmios/actions/workflows/nix.yaml) now produces and upload statically linked binary as build artifacts. They'll also now be tagged and attached to next releases for easy download.

**Comment by kayandra** [comment]
Love you man! Thanks for this. Is there a wallet I can drop a tip? Just to say thank you.

**Comment by KtorZ** [comment]
My pleasure ☺️, thanks for the feedback.
Here's a sponsors page if you may like:

https://github.com/CardanoSolutions/ogmios/blob/master/SPONSORS.md#sponsors

**Comment by kayandra** [comment]
https://cardanoscan.io/transaction/4bb5f0012d9db628d628db931ce375dc029c59bf756f47d6c99e3629de9e5ca2
