### ISSUE TITLE
How do I get the transaction body from a transaction id?

### ISSUE THREAD

**Issue by L-as** [CardanoSolutions/ogmios#141]
Thanks!

**Comment by KtorZ** [comment]
Hi, please see the answer to this question on the Cardano Stack Exchange:

https://cardano.stackexchange.com/questions/4078/is-there-a-way-to-go-from-a-txid-to-a-tx/4483#4483

**Comment by L-as** [comment]
So given a UTXO, there is no way of getting the body of the transaction that it came from?
