### ISSUE TITLE
How to change the default connection protocol

### ISSUE THREAD

**Issue by rumourscape** [CardanoSolutions/ogmios#151]
I am using the ogmios typescript library and it defaults the host connection to ```http``` but I need it to connect to ```https```.
How do I change that? Here's my code.
```typescript
const context : Ogmios.InteractionContext = await Ogmios.createInteractionContext(
		err => console.error(err),
		() => console.log("Connection closed."),
		{ connection: { host: 'ogmios-api.testnet.dandelion.link', port: 80 } }
	)
```

**Comment by KtorZ** [comment]
You can `tls: true` on the connection configuration object: 

https://ogmios.dev/api/interfaces/_cardano_ogmios_client.ConnectionConfig.html#tls

Cheers!
