### ISSUE TITLE
Why pin to Node 14

### ISSUE THREAD

**Issue by longngn** [CardanoSolutions/ogmios#152]
https://github.com/CardanoSolutions/ogmios/blob/master/clients/TypeScript/package.json#L7
Does this mean all consumers have to use Node 14? We're using Node 16 and can't install @cardano-ogmios/client
Node 16 has been LTS recently

**Comment by KtorZ** [comment]
It's merely a choice for build reproducibility, and also indicates that the software is tested only with Node.js@14 at the moment. There's probably no issue with 15 nor 16 though.

We could also very much extend the CI workflow to test for multiple versions actually.

I didn't realize that this would prevent package from being installed from npm 😮!
