### ISSUE TITLE
Docker stop ends in container getting killed

### ISSUE THREAD

**Issue by jondoe1337** [CardanoSolutions/ogmios#168]
#### What Git revision are you using? 
Docker image (latest) with sha256:31747b3178dac8f378a8cf3fbd011fcbd2c849008c4803fde9e320620a40e5cc

#### What operating system are you using, and which version?

- [ x] Linux / Ubuntu
- [x] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 
Executing docker stop on the container takes ages and ends in eventually getting killed by the docker daemon. 

#### What should be the expected behavior?
The container should get stopped within a reasonable amount of time. A container getting killed externally could result in corrupting the database e.g.

**Comment by KtorZ** [comment]
@jondoe1337 what image are we talking about here? The standalone or the one coupled with cardano-node ?

**Comment by jondoe1337** [comment]
Sorry - I was not aware of multiple images being existed:
`cardanosolutions/cardano-node-ogmios:latest`

**Comment by yorickdowne** [comment]
It ignores SIGTERM. Inside docker, but also from tty. If you `docker run` this image, Ctrl-C won't stop it.

**Comment by KtorZ** [comment]
@jondoe1337 I finally took the time to look into this a bit more, and found the issue. The node is actually properly terminated by the stop signal, but not the background ogmios server which keeps running (causing docker to wait and timeout, forcing the container to quit eventually with a SIGTERM). 

I've now fixed that in the supervision script that's used by the cardano-node-ogmios image; I am rebuilding the image to try this out locally. 

--- 

@yorickdowne this is incorrect, the container does react to signals and CTRL-C just fine, but you need to start the container in interactive mode with TTY (`-it`) for this to work. This has nothing to do with **this** image, but is a standard docker behavior.

**Comment by yorickdowne** [comment]
Good to know. In my testing with `-it` it looked like there was a missing `exec` in the wrapper script. Looking forward to the fix!
