### ISSUE TITLE
Support Node 16

### ISSUE THREAD

**Issue by chafnan** [CardanoSolutions/ogmios#169]
Can support for Node 16 please be added?

**Comment by KtorZ** [comment]
Hi, what do you mean by "support for Node 16" ? Is there any features from Node 16 which are incompatible with Node 14 and prevent the TypeScript client from operating normally?

**Comment by chafnan** [comment]
I should have been more clear. Can the engine setting in the `package.json` be removed? As for now it is locked into Node 14, so when installing the package with yarn and having node >14, it is blocked without using the `--ignore-engines` options.

**Comment by chafnan** [comment]
Taking a deeper look at it. It seems that the require was relaxed already from `^14` to `>=14`. That is exactly what I was asking for, but it's not published yet.  I'll just have to wait for the next version to be pushed.

Thanks.

**Comment by KtorZ** [comment]
Hi, the latest version was published 3 days ago on npm, perhaps you missed it :thinking: ? 

https://www.npmjs.com/package/@cardano-ogmios/client/v/5.1.0

**Comment by chafnan** [comment]
Yup, you are right. Thanks for the help.
