### ISSUE TITLE
Individual poolProvenance missing from rewardsProvenance call

### ISSUE THREAD

**Issue by renesecur** [CardanoSolutions/ogmios#171]
#### What Git revision are you using? 
Server 5.0.0, client 5.1.0

#### What operating system are you using, and which version?

- [ X ] Linux / Ubuntu

#### Describe what the problem is? 
I am calling the rewardsProvenance endpoint, which used to provide the full provenance for all pools in the 'pools' attribute, but that attribute is now empty.

#### What should be the expected behavior?
Response includes individual poolProvenance data like so:

```
{
  "pools": {
    "pool1qqqqqdk4zhsjuxxd8jyvwncf5eucfskz0xjjj64fdmlgj735lr9": {
      "totalMintedBlocks": 59,
      "totalStakeShare": "32615299509089/17003998195092006",
      "activeStakeShare": "2965027228099/1069864219685630",
      "ownerStake": 2540213166977,
      "parameters": {
        "id": "pool1qqqqqdk4zhsjuxxd8jyvwncf5eucfskz0xjjj64fdmlgj735lr9",
        "vrf": "6de7605b2afd7e205318fc8b4329d26439b5b179b4746fea12f1ce50395f5d9e",
        "pledge": 2500000000000,
        "cost": 340000000,
        "margin": "1/100",
        "rewardAccount": "stake1uxrkez465cmpdrragd3rhcgrc6lllnasxd7qtl735l489egx9yfxe",
        "owners": [
          "39eb3ba2624bec61801b69cd087c1642a265b3288fb1019faa9e3ea4",
          "3d8c7608966b4bbdf513a14d5961f4d989d96cc8a98f6aed3d67aeea",
          "d122f30e3511c9e4f03575bef483012c9670401b59a368ebbc0a3ef1",
          "f5e5e457287965fd80620eb20ac6ecd31cc2313c0ddd708f65feb9e0"
        ],
        "relays": [
          {
            "hostname": "relays.stakepool.at",
            "port": 3001
          },... 
```

Instead the response looks like this:
```
{
  "pools": {},
  "mintedBlocks": {
    "pool1qqqqqdk4zhsjuxxd8jyvwncf5eucfskz0xjjj64fdmlgj735lr9": 58,
    "pool1qqqqp...
```

**Comment by KtorZ** [comment]
This is odd. I can reproduce as well and I don't think it has anything to do with Ogmios. I see there has been some recent updates in the ledger regarding incremental rewards calculations. I will try to compare with the behavior on 1.32.0.

**Comment by KtorZ** [comment]
I confirm that this works fine on 1.32.0 and latest version of Ogmios. So this is an upstream regression...

**Comment by KtorZ** [comment]
@renesecur may you open an issue on [input-output-hk/cardano-ledger](https://github.com/input-output-hk/cardano-ledger/issues) explaining the issue to the ledger team ? Hopefully, this can still make it for 1.34.*

**Comment by JaredCorduan** [comment]
My apologies, I had thought that this query was going to be deprecated in the node in 1.33.0. Indeed we are deliberately no longer populating that data.
