### ISSUE TITLE
NoDbMarkerAndNotEmpty "/db/protocolMagicId" on testnet

### ISSUE THREAD

**Issue by Jared0430** [CardanoSolutions/ogmios#182]
#### What Git revision are you using? 
v5.2.0
v5.1.0
v5.0.0
v4.2.1

#### What operating system are you using, and which version?

- [X] Linux / Ubuntu
- [x] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 
Running the cardanosolutions/cardano-node-ogmios Docker image in Kubernetes, mainnet versions work fine testnet versions all crash with

```
NoDbMarkerAndNotEmpty "/db/protocolMagicId"

cardano-node: Missing "/db/protocolMagicId" but the folder was not empty%
```

#### What should be the expected behavior?
Container doesn't crash

**Comment by KtorZ** [comment]
Docker images are network-specific, and tagged after the network. Are you running a testnet image or, trying to connect to testnet with a mainnet image?

**Comment by Jared0430** [comment]
Running the network specific container

`cardanosolutions/cardano-node-ogmios:v5.2.0-testnet`

Also tried passing the environment NETWORK=testnet which doesn't have an effect

**Comment by KtorZ** [comment]
Are you mounting the database volumes between your two instances (mainnet and testnet) to the same location? It'd be preferable not too. 

By the way, did you read the [user manual](https://ogmios.dev/getting-started/docker/) regarding docker?

**Comment by Jared0430** [comment]
No they are both using their own volumes. In fact, I ran the testnet one first, when that didn't work I tried the mainnet version and they appears to be syncing ok.

Yes I've read through the documentation but can't find anything that would help with my issue

**Comment by KtorZ** [comment]
It's odd but I am also not familiar with Kubernetes. The docker images are fine. They're even integrated as part of the project continuous integration workflow and used in production and continuous integration in multiple other projects.

I'd suggest to double check your configurations / scripts, and perhaps specificity of Kubernetes itself when it comes to management of containers.

If you figure out the issue, I am happy to add some notice to the user guide about it (or take a PR!).

I can also suggest you to look at similar issues on input-output-hk/cardano-node since the cardano-node-ogmios image is based off that one and the error here suggests something's wrong with the cardano-node setup, not ogmios.

**Comment by Jared0430** [comment]
Ok no worries, I'll report back if I manage to solve it.

Just to double-check, I don't need to specify any env specifically for the testnet version, right? It's all handled within the container?

**Comment by KtorZ** [comment]
Yes indeed. Environment variables are only used during the build phase of the image. Once built, it's already tied to a particular network.

**Comment by Jared0430** [comment]
After some testing, I've noticed that when starting the container with a non-persistent volume it works fine, however as soon as I attach /db to a persistent volume I start getting issues.

Of course, it's essential to use a persistent volume, otherwise the entire db would wipe every time the container restarts with a Kubernetes environment.

I can only assume that persistent volumes have some hidden files in them which is causing the node to throw this error. Is there a way I can override the db location, as I may need to mount the volume to something like /data and have the db sync to /data/db instead, or do I need to make a custom build for this?

**Comment by KtorZ** [comment]
> Is there a way I can override the db location

Using the combined cardano-node-ogmios image no as the image really wraps two processes (cardano-node and ogmios) to run them as one container, and the wrapping script that does so is basic and does not forward any arguments to either of the child processes.

You could give a try to the standalone images of both Ogmios and cardano-node which would give you access to both softwares command lines. You'll need to mount the /ipc volume as a shared volume between ogmios and cardano-node as they both communicate through a Unix domain socket which is by essence, a file.

**Comment by Jared0430** [comment]
Ok I'll give that a try. Thanks for your help.

Not sure how open you would be to changing that directory to /data/db in a future release, might make things easier for other people going forwards too if it has no other effect on the container.
