### ISSUE TITLE
Typescript tx submission client is not able to submit transactions in 5.2.0

### ISSUE THREAD

**Issue by xdzurman** [CardanoSolutions/ogmios#188]
#### What Git revision are you using? 
5.2.0

#### What operating system are you using, and which version?

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 

Using
```
// "@cardano-ogmios/client": "^5.2.0",
const txClient = await createTxSubmissionClient(context)
const txId = await txClient.submitTx('...hexHashTx')
```
results in
```
{\"type\":\"jsonwsp/fault\",\"version\":\"1.0\",\"servicename\":\"ogmios\",\"fault\":{\"code\":\"client\",\"string\":\"Invalid request: field \\\"bytes\\\" not found.\"},\"reflection\":{\"requestId\":\"bEq8z\"}}
```

#### What should be the expected behavior?
The tx should go through and return the tx id, and recognize the `bytes` field deep within. Version 5.1.0 works perfectly, but I need the tx id added in 5.2.0.

**Comment by KtorZ** [comment]
What version of the server are you running? Running a 5.2.0 client against a 5.1.0 server won't work I am afraid. This error suggests that the server is indeed running as 5.1.0.

**Comment by xdzurman** [comment]
Ah, dumb me. Forgot to restart the container. Sorry!
