### ISSUE TITLE
Filtering by address

### ISSUE THREAD

**Issue by siegfried** [CardanoSolutions/ogmios#193]
I saw this statement in the document of API.

```
Filtering UTXO by address is no longer recommended with the introduction of on-disk ledger state storage. Filtering by output reference is preferred.
```

Our dApp has to query all UTxOs of a script address. If this is deprecated, what function shall we use?

**Comment by KtorZ** [comment]
Sadly, there hasn't been any alternative offered in the ledger / node about this. The proper way to tackle this is to build lookup indexes to map addresses to their corresponding output reference, and then use other queries or, the chain-sync protocol to find the relevant data you need.

[Kupo](https://github.com/CardanoSolutions/kupo#readme) offers a configurable a lightweight chain index solution. You might want to look it up.

**Comment by siegfried** [comment]
Thanks. @KtorZ 
Actually the script addresses our dApp needs to query are arbitrary. We don't know which address to query at firsthand, so Kupo and Ogmios might not able to be used.

**Comment by siegfried** [comment]
Cool. Thanks a lot.
