### ISSUE TITLE
EvaluateTx: search in utxoset first

### ISSUE THREAD

**Issue by grim-i-am** [CardanoSolutions/ogmios#201]
#### Describe your idea, in simple words.
Documentation for evaluateTx states:

"Ogmios gives way to provide an additional UTXO set to be used during evaluation. Note that it will still try to resolve inputs that are known, but will use the provided UTXO set as a complement for those that are unknown or yet-to-know"

This implies that UTxOs are first searched for on chain and if not found, ogmios will then search the provided UTxO set.

Assuming that a blockchain search is heavier than a search in the utxo set, and that anyone building the tx to be evaluated already has the UTxO data available (since it's required to create a balanced tx), wouldn't it be more efficient to search the UTxO set first and avoid a ledger search entirely when the UTxO is provided?

#### Why is it a good idea?
It offers a slight optimisation by removing the overhead of searching the blockchain for utxos that are provided in the utxo set.

#### Are you willing to work on it yourself?
I am unable to work on this myself at this stage

**Comment by KtorZ** [comment]
Getting UTxO from the ledger state is achieved in a number of steps which is logarithmic in the size of the UTxO set. This is thus a very efficient operation. Note that there's no "search on chain" for the UTxO corresponds to an accumulated state that is the result of applying blocks.

While it is true that the internal implementation could avoid to perform a ledger query in case where the UTxO is user provided, this is a small enough cost that the overhead and complexity of bypassing aren't worth the trade-off, unless performances really proves to be bad. So far, the call range in about 10-200ms dependinf on the complexity of the transaction, which seems pretty efficient as such.

Did you experience any slowness which motivated the ticket?

**Comment by grim-i-am** [comment]
> Did you experience any slowness which motivated the ticket?

Hi, I was just going through the documentation before using Ogmios in my project and this just stuck out to me as (what I thought to be) a low-hanging optimisation candidate. As I said in my OP, my suggestion was based on a couple of assumptions. I didn't realise that switching the order of the searches would have much of an overhead and complexity, I imagined it to be as simple as swapping the order of the calls to the search functions.

For example, instead of:
`utxo = searchLedger(tx-in) || searchUtxoSet(tx-in)`

it would be:
`utxo = searchUtxoSet(tx-in) || searchLedger(tx-in)`

or something similar.

In my case I will always know all of the Utxos that I will use in my txns and will provide them in the utxo set so the ledger query will always be redundant.

Anyway, c'etait juste une suggestion :)

I'll close the ticket, thanks.

**Comment by KtorZ** [comment]
Got you!
