### ISSUE TITLE
First response after FindIntersect(origin) and RequestNext is a RollBackward

### ISSUE THREAD

**Issue by grim-i-am** [CardanoSolutions/ogmios#202]
Is it normal that I'm getting a RollBackward message after FindIntersect origin, and request next.

I've tested on both testnet and mainnet. My program goes into an infinite loop.
```
Sending: FindIntersect { points: [ 'origin' ] } undefined

OnMessage
MethodName: FindIntersect
    Result: {"IntersectionFound":{"point":"origin","tip":{"slot":55041077,"hash":"83fde63addd4d163169af55ece8350f392677fcd42b33fe9e7fc084087e4b9a4","blockNo":3458640}}}
Reflection: null

Sending: RequestNext {} { n: 2 }

OnMessage
MethodName: RequestNext
    Result: {"RollBackward":{"point":"origin","tip":{"slot":55041077,"hash":"83fde63addd4d163169af55ece8350f392677fcd42b33fe9e7fc084087e4b9a4","blockNo":3458640}}}
Reflection: {"n":2}

Sending: FindIntersect { points: [ 'origin' ] } undefined

OnMessage
MethodName: FindIntersect
    Result: {"IntersectionFound":{"point":"origin","tip":{"slot":55041077,"hash":"83fde63addd4d163169af55ece8350f392677fcd42b33fe9e7fc084087e4b9a4","blockNo":3458640}}}
Reflection: null

Sending: RequestNext {} { n: 2 }

OnMessage
MethodName: RequestNext
    Result: {"RollBackward":{"point":"origin","tip":{"slot":55041077,"hash":"83fde63addd4d163169af55ece8350f392677fcd42b33fe9e7fc084087e4b9a4","blockNo":3458640}}}
Reflection: {"n":2}

Sending: FindIntersect { points: [ 'origin' ] } undefined

OnMessage
MethodName: FindIntersect
    Result: {"IntersectionFound":{"point":"origin","tip":{"slot":55041077,"hash":"83fde63addd4d163169af55ece8350f392677fcd42b33fe9e7fc084087e4b9a4","blockNo":3458640}}}
Reflection: null

Sending: RequestNext {} { n: 2 }

OnMessage
MethodName: RequestNext
    Result: {"RollBackward":{"point":"origin","tip":{"slot":55041077,"hash":"83fde63addd4d163169af55ece8350f392677fcd42b33fe9e7fc084087e4b9a4","blockNo":3458640}}}
Reflection: {"n":2}
```

**Comment by KtorZ** [comment]
Yes, this is the expected behavior. Upon a successful intersection, the node will always ask you to first rollback to the agreed point of intersection. 

I am not sure what your program is doing but you're probably not handling rollbacks correctly. In principle, clients following the chain-sync protocol can be relatively "dumb", and be guided by the protocol. The protocol is stateful and the state is maintained by the server (the node). This is very well tailored to event-loops and event-sourcing types of applications where your own client state is modeled as a sequence of events. Rolling back is then synonyms of dropping all the events beyond the point of rollback.

**Comment by grim-i-am** [comment]
Ok, I think I understood my issue. Rollback is actually a message for me to rollback my state. I was handling the rollback by asking Ogmios to FindIntersect the point returned by the rollback.

Merci encore

**Comment by grim-i-am** [comment]
actually, one more comment. Having the result name as a key rather than a value makes it impossible to use an evaluate to handle the different results. Instead we need to have a list of if/elses.

**Comment by KtorZ** [comment]
That last point is something someone else raised in the past also, working with Kotlin.
This is actually not true for every language / environment, originally, I mostly tailored Ogmios to js-like environment for which the current approach works great. It's also fine in Haskell, Rust or languages which support algebraic data types in general. I reckon it doesn't play well with Python, Ruby and the like where structures like this aren't really first class citizen.

Out of curiosity, what environment are you in?

**Comment by KtorZ** [comment]
Note that this will most likely change in the next major release, but if requires a major bump since it'd completely break the API!

**Comment by grim-i-am** [comment]
Back-end is NodeJS. 

I meant "switch" when i said "evaluate" earlier - that was a brain fart. "Evaluate" comes from my COBOL days but its been 17 years since I last touched that so I have no idea where that came from, lol.

How could I use the key in a switch statement? (unless I use "switch (true)")

At the moment it is:
```
if (response.result.RollBackward) {
   ...
} else if (response.result.RollForward) {
   ...
} else if (response.result ....)
```

I suppose I could have:
```
switch (true) {
case response.result.RollBackward != false:
```

but I don't really like that.

if it were:
```
switch response.result.type {
case "RollBackward":
   ...
   break;

case "RollForward":
   ....
```

it would be nicer (in my view)

**Comment by KtorZ** [comment]
The way I approach this is usually to switch on the `response.methodname` and then, handle each method response accordingly. So then, yes, there's usually still a `if` between forward/backward for handling the `RequestNext` response.

**Comment by grim-i-am** [comment]
I like this tool. Playing around with the various functions is filling my head with ideas :smiley:

**Comment by KtorZ** [comment]
Thanks for your feedback by the by :blush: ! 

If you want to showcase your project also, or discuss some idea, do not hesitate to open a [Github Discussion](https://github.com/CardanoSolutions/ogmios/discussions)
