### ISSUE TITLE
Docker-machine is deprecated and archived - please update instructions for deploying to AWS

### ISSUE THREAD

**Issue by naeri-kailash** [CardanoSolutions/ogmios#207]
#### What operating system are you using, and which version?

- [ ] Linux / Ubuntu
- [ ] Linux / Other
- [x] OSX
- [ ] Windows

#### Describe what the problem is? 

Hi there, I was following your instructions here https://ogmios.dev/deployment/aws/ to deploy a cardano node/ogmios set to AWS, however the tool `docker-machine` is no longer available, I was hoping you could update the instructions to use some current tooling so that I and future users can complete the task, thanks so much!

**Comment by naeri-kailash** [comment]
Actually the tool still can be installed with brew but documentation and support have been removed :)

**Comment by KtorZ** [comment]
Doh. That's a bummer; it was quite a handy tool. Perhaps the whole thing could be replaced with a Terraform configuration or something alike, that would make it easy to deploy an instance in one instruction.
