### ISSUE TITLE
Error in stack build ogmios

### ISSUE THREAD

**Issue by shishirhome** [CardanoSolutions/ogmios#216]
#### What operating system are you using, and which version?

- [ ] OSX

#### Ogmios build is failing? 

stack build ogmios
Cloning 1a9ec4ae9e0b09d54e49b2a40c4ead37edadcce5 from https://github.com/input-output-hk/cardano-ledger
Cloning 1a9ec4ae9e0b09d54e49b2a40c4ead37edadcce5 from https://github.com/input-output-hk/cardano-ledger
Received ExitFailure 128 when running
Raw command: /usr/bin/git clone https://github.com/input-output-hk/cardano-ledger /private/var/folders/60/04rpxn6x6sxbd3znjh19kvnm0000gp/T/with-repo10736/cloned
Standard error:

Cloning into '/private/var/folders/60/04rpxn6x6sxbd3znjh19kvnm0000gp/T/with-repo10736/cloned'...
error: RPC failed; curl 56 LibreSSL SSL_read: error:02FFF036:system library:func(4095):Connection reset by peer, errno 54
error: 7150 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Even though all my connections are prefect**

**Comment by shishirhome** [comment]
**Same error in execute the command:-** 

stack exec -- ogmios --help
Cloning 1a9ec4ae9e0b09d54e49b2a40c4ead37edadcce5 from https://github.com/input-output-hk/cardano-ledger
Cloning 1a9ec4ae9e0b09d54e49b2a40c4ead37edadcce5 from https://github.com/input-output-hk/cardano-ledger
Received ExitFailure 128 when running
Raw command: /usr/bin/git clone https://github.com/input-output-hk/cardano-ledger /private/var/folders/60/04rpxn6x6sxbd3znjh19kvnm0000gp/T/with-repo10987/cloned
Standard error:

Cloning into '/private/var/folders/60/04rpxn6x6sxbd3znjh19kvnm0000gp/T/with-repo10987/cloned'...
error: 6307 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by KtorZ** [comment]
I am afraid that building on OSX is not something that is currently supported. Though, this is orthogonal to ogmios here and sounds like more a problem with `stack`. 

Note that in principle, you should also be able to build with `cabal` if that is any more convenient for you.
