### ISSUE TITLE
Server should warn clients when using unexpected fields in requests. 

### ISSUE THREAD

**Issue by grim-i-am** [CardanoSolutions/ogmios#217]
#### What Git revision are you using? 
v5.3.0 binary

#### What operating system are you using, and which version?

- [ ] Linux / Ubuntu
- [X] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 
When calling "Query/FindIntersect/RequestNext" methods with a reflection parameter, the reflection object is not sent to onMessage handler.
 
#### What should be the expected behavior?
Reflection parameter should always be reflected.

**Comment by KtorZ** [comment]
I have never observed such behavior :thinking: , are you looking at the right parameter? In requests, the reflection parameter is called `mirror`. Settings `reflection` as a parameter on requests will have no effect.

**Comment by grim-i-am** [comment]
Sorry, my mistake

**Comment by KtorZ** [comment]
I think it's still worth adding some little code in the query parser to reject requests which would contain additional parameters, and in particular, a `reflection` parameter. 

Mind if I rename the ticket to reflect this?

**Comment by grim-i-am** [comment]
> Mind if I rename the ticket to reflect this?

not at all, be my guest!
