### ISSUE TITLE
Possible to list delegators and live stake per pool?

### ISSUE THREAD

**Issue by bravo-kernel** [CardanoSolutions/ogmios#227]
Hi there, 

We are looking to generate **a list of all delegators and their live stake for any given pool**. Would that be possible using (only) Ogmios or should we turn to other tooling?

Result should be something similar to:

```json
[
  {
		"address": "stake1u8mq54ph49h6fnt9k2wr75lt35mq03apyvd8adk9s3ax7us0htcz8",
		"liveStake": "3666"
	},
	{
		"address": "stake1u8c5kwrsuf706ezy5f9cy9rwnux5g3f93pqpwwtdw30udqc0df500",
		"liveStake": "1720248149"
	}
]
```

**Comment by KtorZ** [comment]
There's currently no direct query that does this unfortunately. This could be implemented through the chain-sync protocol however, by monitoring delegation certificates.

I imagine however that it could be easily added upstream in the node which likely already track this information in some form or another.

**Comment by bravo-kernel** [comment]
Thanks for confirming that this is indeed (currently) not possible. 

Are you suggesting a feature request for cardano-node/cardano-cli?

**Comment by KtorZ** [comment]
More for the networking. The mini protocols are mostly in the lands of ouroboros-network. Provided that the information is available in the ledger. In this case, I think it is, so it's probably just a matter of adding the query.

I can look into it. I think there's indeed value in it.

**Comment by bravo-kernel** [comment]
That would be very much appreciated. The question pops up all over the place. 

Much ❤️
