### ISSUE TITLE
WebSocket immediate disconnect on vasil-dev network

### ISSUE THREAD

**Issue by rhyslbw** [CardanoSolutions/ogmios#230]
#### What Git revision are you using? 
e3b53aa5b2dac80fc80ea61982a6e555494399cb

https://github.com/input-output-hk/cardano-configurations/commit/77ad26a3c6efe5a6982652cb142f6cdd573c92ba

#### What operating system are you using, and which version?

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is?

Connections made to the Ogmios server on _vasil-dev_ result in an immediate WebSocket close:

##### Server logs
``` console
cardano-node-ogmios_1  | {"severity":"Error","timestamp":"2022-06-23T15:17:04.942155567Z","thread":"49","message":{"WebSocket":{"exception":"MuxError MuxBearerClosed \"<socket: 18> closed when reading data, waiting on next header True\"","tag":"WebSocketUnknownException"}},"version":"v5.5.0"}
cardano-node-ogmios_1  | {"severity":"Info","timestamp":"2022-06-23T15:17:04.942280371Z","thread":"49","message":{"WebSocket":{"tag":"WebSocketConnectionEnded","userAgent":"User-Agent unknown"}},"version":"v5.5.0"}

```

##### To reproduce
1. Start an instance of `cardano-node-ogmios` in the _vasil-dev_ network.
2. Change https://github.com/CardanoSolutions/ogmios/blob/e3b53aa5b2dac80fc80ea61982a6e555494399cb/clients/TypeScript/packages/repl/src/index.ts#L29 to: `const context = await createInteractionContext(console.error, (code) => { log(code) }, { connection })` (not sure why I didn't log the disconnect in the initial impl) :no_mouth: 
3. In `clients/TypeScript` run `yarn repl:start --port __`
4. Observe the disconnect code `1006`

#### What should be the expected behavior?

Repeat steps 1,2, and 4 with a _testnet_ instance to observe correct behaviour of no disconnect, and the ability to issue commands.

**Comment by KtorZ** [comment]
@rhyslbw silly question but, did you build the image with the right network configuration (a.k.a vasil-dev?). I just noticed, while trying on my end, that the first 'git clone' step was actually getting cached and, I ended up with a version of the config repository that was quite old, missing the vasil-dev configuration altogether. 

I fixed that in: e4b0cdccccccfe9b3f85968d752b493217e645de and also added `vasil-dev` to the targets for the package workflow. I just tried pulling the image and running the container:

```
docker pull cardanosolutions/cardano-node-ogmios:latest-vasil-dev
docker run -it --name cardano-node-ogmios -p 1337:1337 cardanosolutions/cardano-node-ogmios:latest-vasil-dev
```

And so far, it seems to work fine _outside of the TypeScript client_ but I do indeed observe this with the repl as well :thinking: ... I've been able to run pure JavaScript queries without problems, like:

```js
import WebSocket from 'ws';

const client = new WebSocket("ws://localhost:1337");

client.on('message', e => {
  console.log(JSON.stringify(JSON.parse(e).result, null, 2));
  client.close();
});

client.on('open', () => {
  client.send(JSON.stringify({
    "type": "jsonwsp/request",
    "version": "1.0",
    "servicename": "ogmios",
    "methodname": "Query",
    "args": {
      "query": "ledgerTip"
    }
  }));
})
```

But somehow, the repl just dies.

**Comment by KtorZ** [comment]
Hmmm. It seems like the synchronization is stuck in Alonzo:

```
  "lastKnownTip": {
    "slot": 1325776,
    "hash": "c3cdc755cb6b91371432aa518b52c4e703d3df865d32471a9446af1444620362",
    "blockNo": 57825
  },
  "lastTipUpdate": "2022-06-26T09:16:33.156222502Z",
  "networkSynchronization": 0.77885,
  "currentEra": "Alonzo",
```

So I am thinking that perhaps, it is the background chain-sync that is just choking on the first Babbage's block.

**Comment by KtorZ** [comment]
So, this indeed happens as a result of running the chain-sync protocol and it doesn't seem related to a point on the chain. Indeed, if I run it in a pipelined mode, I can reach ~slot 400 008, but if I run a one-by-one mode, I don't even reach slot 50 000 before the connection closes. In all cases (tried out ~20 times with different modes and starting points), the connection closes after exactly 3.1s. 

There's no trace in the node I could correlate to this. The connection is just abruptly closed.

**Comment by KtorZ** [comment]
I've tried on the testnet and mainnet and as far as I can tell, this behavior doesn't occur there. I wonder if this has anything to do with the issues regarding other peers (namely, the one using an invalid network magic and the one that is propagating bad blocks).

**Comment by rhyslbw** [comment]
Thanks @KtorZ

> did you build the image with the right network configuration (a.k.a vasil-dev?)

I did a `--no-cache` build, so didn't hit the stale cache

> I wonder if this has anything to do with the issues regarding other peers (namely, the one using an invalid network magic and the one that is propagating bad blocks).

:thinking:

**Comment by james-iohk** [comment]
@KtorZ Your node getting stuck is probably a result of using cardano-node:1.35.0-rc3. From RC4 that should not be a problem. Now it's best best to bump to 1.35.0. Also, in case Ogmios depends on the cost model, consider that alonzo-genesis file is missing PlutusV2 cost model.

**Comment by james-iohk** [comment]
@KtorZ Yeah, the PlutusV2 cost model was excluded by mistake when vasil-del was spun up. Then, instead of resetting the network, an update proposal was issued to include the V2 cost model. If possible, it would be safer for Ogmios to query the node for protocol params rather than depend on the file.

**Comment by KtorZ** [comment]
Trying to run the node with p2p disabled, I can confirmed that the behavior isn't present anymore. I can keep the repl open and do chain-sync just fine (or at least, for more than 3s and up until my current node's state). Though, I haven't yet figured what the topology configuration should be in non-p2p mode on `vasil-dev`, so my node is just hanging there not syncing. 

This is the case also with `1.35.0`. Running with `EnableP2P` causes the client connection to be terminated after 3s :shrug: ... And there's no trace on the node's side (even after enabling more logs on the local chain sync).  I am.. puzzled.

**Comment by KtorZ** [comment]
What also puzzles me is that, there's also an internal client connection that Ogmios uses for the health heartbeat. This one is basically a chain-sync, and it remains up and running without problem :thinking:

**Comment by KtorZ** [comment]
Hypothesis above :point_up:  confirmed, so the second client (which is basically just idling waiting for a request) is indeed terminated automatically after ~3s somehow, causing the other to fail. If I simply add an error handling on that second client and forever restart it, then the rest seems fine.

So, we have a "quickfix" / mitigation, which is good. But it doesn't quite explain _why_ the second client is terminated and why this only occurs during p2p.

**Comment by KtorZ** [comment]
It seems that the problem comes with the (second) client connecting but not actually sending any message; causing the node to probably clean up the connection? I've slightly change the second client such that it sends a dummy message when connecting, **and then** awaits for requests and it seems to go through, at least a little longer (I can do a full chain-sync and the connection remains open until the end). 

I assume that this is perhaps something configurable and now makes me wonder.. will the node automatically terminates the connection should there be no client activity for X minutes or hours. That'd be pretty annoying :grimacing: ... Need to ask Marcin.

**Comment by KtorZ** [comment]
@rhyslbw The commit above does partially fix the problem but it raises also a few questions. I say partially because, the same behavior can still be observed if the client does not send any request within a short enough time window (which seems to be ~2s).  For example:

```js
client.on('open', () => {
  setTimeout(() => {
    client.send(requestNext);
  }, 2000);
});
```

This fails for me and gives me an error `1006 connection closed`. But, anything below that seems to work fine. And it seems to only be a problem for the **first message**. So, if I send a first request promptly, I can wait a lot longer between messages afterwards (I've been up to one minute without problem). 

Again, this is a bit odd and I hope configurable so I can probably set that to _infinity_ :grimacing:

**Comment by KtorZ** [comment]
Marcin confirms that this is a strange behavior and, to quote him: 

> In P2P we have a timeout which shuts down a connection if nothing happens after one negotiated a connection. My hypothesis is that this timeout is also set for node-to-client connection, but it should only be set for node-to-node connections. 
>
> If my hypothesis is right, your solution will actually solve the problem (although the right thing is to remove the timeout from node-to-client protocol).

Looks like we're going to need a `1.35.1` :no_mouth:

**Comment by rhyslbw** [comment]
Thanks for the detailed investigation notes @KtorZ. I'm attempting to see if we can work around this by joining the network without enabling p2p, but am stuck since I'm not sure what the relay address is. Have you considered this as a workaround?

**Comment by KtorZ** [comment]
Yes but, I am not even sure that there are relays available...

**Comment by rhyslbw** [comment]
https://github.com/input-output-hk/cardano-world/blob/d6bdf6024d94bd48c47e00c9316c25eecae26735/nix/cardano/environments/default.nix#L167-L186

**Comment by KtorZ** [comment]
https://github.com/input-output-hk/ouroboros-network/pull/3844 :tada:
