### ISSUE TITLE
[Typescript client] LocalTxMonitor not showing any transactions from the mempool

### ISSUE THREAD

**Issue by Et9797** [CardanoSolutions/ogmios#232]
Using the Typescript localTxMonitor code example I am not getting shown any transactions that are in my local node's mempool. The first `nextTx` always returns `null`, no matter what. The ChainSyncClient, however, works completely fine. Could it be something to do with the fact that I am using the combined cardano node + ogmios docker container?

**Comment by KtorZ** [comment]
Hey, do you actually submit any transactions to your node? If you don't, then it is normal not to see any transaction in your mempool, especially if your node isn't a block producing node. 

(regarding your hypothesis with the container, I am rather certain that it isn't causing any problem of this nature).

**Comment by Et9797** [comment]
> Hey, do you actually submit any transactions to your node? If you don't, then it is normal not to see any transaction in your mempool, especially if your node isn't a block producing node.
> 
> (regarding your hypothesis with the container, I am rather certain that it isn't causing any problem of this nature).

I see, thank you. It is indeed just a regular node. I was under the impression that all nodes have txs in their mempool, albeit not an exact copy to that of other nodes, and that you'd be able to inspect them with this protocol.
