### ISSUE TITLE
Block type optional properties.

### ISSUE THREAD

**Issue by MarcelKlammer** [CardanoSolutions/ogmios#238]
the block types

BlockShelley
BlockAllegra
BlockMary
BlockAlonzo
BlockBabbage

in

@cardano-ogmios/schema

have the ? (optional) modifier set for their properties:

body?
headerHash?
header?

See here: https://github.com/CardanoSolutions/ogmios/blob/d4d27a7841688e330f82ebad9db5e9879bf2bbaf/clients/TypeScript/packages/schema/src/index.ts#L1349

This ? (optional) modifier should be removed, as those properties of a block are actually not optional.

**Comment by KtorZ** [comment]
Ho! Good catch. The JSON specification (which is the source from which the TypeScript type definitions are generated) is missing a `required` field to make those properties non-optional.
