### ISSUE TITLE
Missing documentation for Local-Tx-Submit collectErrors result

### ISSUE THREAD

**Issue by AndrewWestberg** [CardanoSolutions/ogmios#244]
#### What Git revision are you using? 
Latest

#### What operating system are you using, and which version?

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 
Missing documentation

#### What should be the expected behavior?
Return types should be documented.

**Comment by KtorZ** [comment]
Fixed in https://github.com/CardanoSolutions/ogmios/commit/952628d198039b0cb6f666a901809c01ab0b8678
