### ISSUE TITLE
`slotLength` should be a float

### ISSUE THREAD

**Issue by klntsky** [CardanoSolutions/ogmios#245]
#### Describe what the problem is? 

It looks like `slotLength` values of `eraSummaries` is rounded to an integer, but actually fractional values are possible too.

E.g. [here](https://github.com/mlabs-haskell/plutip/blob/26f77d18f356911ccb96861b1c193fa90e155417/cluster-data/shelley-genesis.yaml#L53). 

We are having troubles with [Plutip](https://github.com/mlabs-haskell/plutip) integration in CTL when using time conversions: https://github.com/Plutonomicon/cardano-transaction-lib/issues/868#issuecomment-1210987889 

#### What should be the expected behavior?

Can we change the type of `slotLength` to floating-point number?

**Comment by KtorZ** [comment]
Arg. That's correct, the JSON encoding relies on some function from [cardano-base](https://github.com/input-output-hk/cardano-base/) which does an unsafe conversion to seconds as integers. 

I am not a huge fan of floating numbers in interfaces / serializations, but for slot-lengths that sounds reasonable (if only to maintain backward-compatibility for integer values). 

Thanks for reporting!
