### ISSUE TITLE
Ogmios v5.5.5_1.35.3 for the Testnet

### ISSUE THREAD

**Issue by fmira21** [CardanoSolutions/ogmios#254]
Hi guys!
I have one Testnet node.
Currently I am updating the second one, but cannot find v5.5.5_1.35.3 for Testnet. Where can I find this image?

Thank you in advance!

**Comment by KtorZ** [comment]
There's none. Testnet is broken since 1.35.2 and should be taken down anytime soon. Thus, we no longer build images for it.

Instead, use images for pre-prod or preview wuihh are the new testnets 👍
