### ISSUE TITLE
Use of colon (ogmios.v1:compact) in sub-protocol is out of RFC

### ISSUE THREAD

**Issue by rdlrt** [CardanoSolutions/ogmios#272]
#### Describe what the problem is? 

Just a minor change request for v6 (created issue just so that it's easier to track) to [remove colon character](https://github.com/CardanoSolutions/ogmios/blob/0f728689094b4c7ef09dcf0c9011cbcaeacc4d1a/server/src/Ogmios/App/Server/WebSocket.hs#L222) used in sub-protocol to ensure conformance to RFC6455.

**Comment by KtorZ** [comment]
Added to: https://github.com/CardanoSolutions/ogmios/discussions/263
