### ISSUE TITLE
No support for stake script rewards

### ISSUE THREAD

**Issue by klntsky** [CardanoSolutions/ogmios#277]
#### Describe what the problem is? 

It looks like Ogmios only support querying stake rewards for PubKey hashes, there's no ScriptHash support:

1. https://github.com/CardanoSolutions/ogmios/blob/7a039607bfb982ddcba8ef9f6c83afeeb7776974/server/src/Ogmios/Data/Json/Query.hs#L904
2. https://github.com/CardanoSolutions/ogmios/blob/7a039607bfb982ddcba8ef9f6c83afeeb7776974/server/src/Ogmios/Data/Json/Query.hs#L1589
3. https://github.com/input-output-hk/cardano-ledger/blob/9a25a43f3970941a2cd64029f7ce667b48832635/libs/cardano-ledger-core/src/Cardano/Ledger/Credential.hs#L73

#### What should be the expected behavior?

We need this kind of query to work with script hashes as well for [CTL](https://github.com/Plutonomicon/cardano-transaction-lib/issues/1060).

**Comment by KtorZ** [comment]
Closed in 1495b4f5655ad61b03f5318187a3adbebd9e5144
