### ISSUE TITLE
docker preview and preprod

### ISSUE THREAD

**Issue by kang-chen** [CardanoSolutions/ogmios#284]
Using docker hub with tags:

:latest-preprod
:latest-preview

getting:

```
Shutting down..
NetworkMagicMismatch "/db/protocolMagicId" (NetworkMagic {unNetworkMagic = 764824073}) (NetworkMagic {unNetworkMagic = 1})

cardano-node: Wrong NetworkMagic in "/db/protocolMagicId": NetworkMagic {unNetworkMagic = 764824073}, but expected: NetworkMagic {unNetworkMagic = 1}%   
```    

is a config fix necessary to replace the network magic numbers? or I'm doing something wrong with running the combined version.

going off readme instructions:

` docker run -it \
  --name cardano-node-ogmios \
  -p 1337:1337 \
  -v cardano-node-ogmios-db:/db \
  cardanosolutions/cardano-node-ogmios:latest-preprod`

**Comment by KtorZ** [comment]
It seems like you're mounting your cardano-node database volume where there's already a mainnet database.

I encourage you to add a network-specific prefix or suffix to the host volume name to avoid this kind of mistake:

`-v cardano-node-ogmios-db-preprod:/db`

**Comment by kang-chen** [comment]
thanks, going to give it a shot. Was going to close issue but I see you've tagged this. Want to keep it open?

**Comment by KtorZ** [comment]
Indeed, I'd like to perhaps review the doc to see if something could be added to prevent others from tripping on this.
You're not the first one to raise this.
