### ISSUE TITLE
Invalid WebSocket subprotocol

### ISSUE THREAD

**Issue by alessandrokonrad** [CardanoSolutions/ogmios#286]
#### What Git revision are you using? 

Ogmios v5.5.1
c32341e56ccbeb1cf1e803d4607699668a1e2cc2

#### What operating system are you using, and which version?

- OSX

#### Describe what the problem is? 

The Deno/browser WebSocket implementation doesn't allow to use the subprotocol `ogmios.v1:compact` for compact serialization. I figured it was because of the colon. Maybe it should be changed to `ogmios.v1.compact`?
This error I'm getting is: 
- ` Invalid protocol value.` (Deno)
- ` Failed to construct 'WebSocket': The subprotocol 'ogmios.v1:compact' is invalid.` (Browser)

**Comment by KtorZ** [comment]
Indeed, as mentioned in: https://github.com/CardanoSolutions/ogmios/issues/272

The compact mode is gone in `v6`; so there will be no sub-protocol at all. Ogmios will be more compact _by default_ (while still providing all necessary information).
