### ISSUE TITLE
Datum type is defined as `{ [k: string]: unknown; } | Datum (string)  | Null` but it looks like it is always returned as a string 

### ISSUE THREAD

**Issue by AngelCastilloB** [CardanoSolutions/ogmios#299]
I am currently working on a feature on our project to map objects returned by Ogmios to our own Core types, during the mapping we notice that the Datum type in Ogmios inside the TxOut is defined as:

```
    datum?: {
        [k: string]: unknown;
    } | Datum | Null;
```

Where Datum is:

```
type Datum = string;
```

Looking at the code in Ogmios it seems that Datum is always encoded as a hex string, so we were wondering why the type is defined as such in Ogmios and if we should be mindful of this or we can safely assume it will always be a hex string. Also, if it is possible for Ogmios to return the datum as `[k: string]: unknown;`, our interpretation of this is that the datum would be encoded as following:

```
{
  '0': 0x18,
  '1': 0x12,
  '2': 0x01,
  '3': 0x46,
  '4': 0x00
}
```

Where the key is the index and the value is the byte value at that position, would this be correct?

**Comment by KtorZ** [comment]
This is for backward-compatibility since the Babbage era. See the release notes (Change section) for v5.5.0: https://github.com/CardanoSolutions/ogmios/releases/tag/v5.5.0

This will be fixed in v6.

**Comment by KtorZ** [comment]
Yes indeed.
