### ISSUE TITLE
delegationsAndRewards for redeemer based address unavailable. 

### ISSUE THREAD

**Issue by leo42** [CardanoSolutions/ogmios#305]
### What Git revision / release tag are you using? 
Whatever demeter.run is using 

### Do you use any client SDK? If yes, which one?
Lucid

### Describe what the problem is?
Querying delegationsAndRewards on a Credential hash(as opposed to key hash) returns nothing.
Example (addr_test1xrxezetp08yvhv6tspez4nyucaq5n5nnucjgshd2ev2kndwdj9jkz7wgewe5hqrj9txfe36pf8f88e3y3pw64jc4dx6s7cmkvx, on preprod) (credential hash ["cd91656179c8cbb34b80722acc9cc74149d273e624885daacb1569b5"]) 

### What should be the expected behavior?
It should be able to get the delegation of stake address created from redeemer scripts,
In the affromentioned example I would expect {
delegate:"pool1tjc56tq7adk64nnq2ldu3f4nh6sxkphhmnejlu67ux7acq8y7rx"
rewards:0}

**Comment by KtorZ** [comment]
Hey, this address is associated with a script hash. So for this query, you need to pass-in the argument as bech32 using the prefix `script` or as a stake address directly -- using the prefix `stake` and the appropriate header.  For example, in your case, you can try:

`script1ekgk2cteer9mxjuqwg4ve8x8g9yayulxyjy9m2ktz45m23x5chj`

I added some extra description in the API reference to make this a bit clearer.

**Comment by leo42** [comment]
Yes this should work. 

Thank you I did not know bech32 was an option.
