### ISSUE TITLE
API docs missing

### ISSUE THREAD

**Issue by karleitner** [CardanoSolutions/ogmios#322]
A lot of the API docs on https://ogmios.dev/api/ went missing, such as Block or TxBabbage schemas. These used to exist a few weeks ago.

**Comment by KtorZ** [comment]
Yes. Ogmios is currently migrating towards v6. The entire API has been re-written and it is a work in progress that will be finalized over the upcoming days. The website only shows the latest version. 

The old JSON schema is still available in the git history: https://github.com/CardanoSolutions/ogmios/blob/v5.6.0/docs/static/ogmios.wsp.json
