### ISSUE TITLE
ECS container  memory and cpu

### ISSUE THREAD

**Issue by NanuIjaz** [CardanoSolutions/ogmios#324]
Hi , ktorz,

I deployed ogmios node (mainnet) as aws fargate service 2 days ago, its still syncing. Not sure if this crashed in the middle. 
Can you help me setting up memory and cpu for the ecs container? 
currently i am allocating 8gb and 512ms. This works in preprod.

**Comment by rdlrt** [comment]
Check Technical Specification in [latest node notes](https://github.com/input-output-hk/cardano-node/releases/latest), ogmios by itself has a very low footprint - tho you might want to keep a couple of GB for future expansion.

**Comment by KtorZ** [comment]
@NanuIjaz could you confirm that you're indeed deploying a *cardano* node with an Ogmios server (ie the cardano-node-ogmios docker image)?

**Comment by NanuIjaz** [comment]
yes, i am deploying "cardano-node-ogmios " into aws ecs.

**Comment by KtorZ** [comment]
So, as @rdlrt said. You need to follow the recommandations for the node as you are effectively a cardano node AND and Ogmios server.
