### ISSUE TITLE
Certificate stake credentials only contains the hash but not the type (key hash/ script hash)

### ISSUE THREAD

**Issue by AngelCastilloB** [CardanoSolutions/ogmios#325]
### What Git revision / release tag are you using?

5.6.0

### Do you use any client SDK? If yes, which one?

TypeScript

### Describe what the problem is?

Some of the certificates that contain stake credentials only contain the hash but not the type, for example:

https://github.com/CardanoSolutions/ogmios/blob/master/clients/TypeScript/packages/schema/src/index.ts#L563-L586

### What should be the expected behavior?

The stake credential should be represented by the hash and the type (key hash or script hash): https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl#L217-L220

**Comment by KtorZ** [comment]
You're looking at the schema for the (unreleased) v6.0.0 while using v5.6.0 which not incompatible (hence the major bump). In particular, the representation has been greatly reworked in v6.0.0 to include a type discriminant at the field level. 

v6.0.0 will be released anytime this week. So stay tuned.
