### ISSUE TITLE
LedgerStateQueryClient.networkBlockHeight not working on TypeScript SDK

### ISSUE THREAD

**Issue by pedromtcosta** [CardanoSolutions/ogmios#330]
### What Git revision / release tag are you using?

6.0.0

### Do you use any client SDK? If yes, which one?

TypeScript

### Describe what the problem is?

I am trying to use the `LedgerStateQueryClient` to get the `networkBlockHeight` with the following code:
```js
const ws = new WebSocket('ws://myogmiosinstance.com:1337');
ws.on('open', async () => {
  const client = await createLedgerStateQueryClient({
    connection: {
      host: 'myogmiosinstance.com',
      port: 1337,
      address: {
        http: 'http://myogmiosinstance.com:1337',
        webSocket: 'ws://myogmiosinstance.com:1337',
      },
      maxPayload: 1000000,
      tls: false,
    },
    socket: ws,
  });

  const h = await client.networkBlockHeight();

  console.log('Network block height:', h);
});
```
The problem is that the `await client.networkBlockHeight()` just hangs and never returns. It works just fine when I try it using the version `5.6.0`:
```js
const ws = new WebSocket('ws://myogmiosinstance.com:1337');
ws.on('open', async () => {
  const client = await createStateQueryClient({
    connection: {
      host: 'myogmiosinstance.com',
      port: 1337,
      address: {
        http: 'http://myogmiosinstance.com:1337',
        webSocket: 'ws://myogmiosinstance.com:1337',
      },
      maxPayload: 1000000,
      tls: false,
    },
    socket: ws,
    afterEach: (msg) => {
      msg();
    }
  });

  const h = await client.blockHeight();

  console.log('Network block height:', h);
});
```

### What should be the expected behavior?

the `await client.networkBlockHeight()` call from version `6.0.0` should work just as `await client.blockHeight()` from `5.6.0`

**Comment by KtorZ** [comment]
I am unable to reproduce this using Ogmios `v6.0.0-rc2` and cardano-node `v8.1.2`. I wonder if you perhaps used Ogmios v6+ with an old (e.g. `1.35.7`) cardano-node version?
