### ISSUE TITLE
Chain Sync DeserialiseFailure on Sanchonet

### ISSUE THREAD

**Issue by mkazlauskas** [CardanoSolutions/ogmios#332]
### What Git revision / release tag are you using?

v6.0.0 (rc2)

### Do you use any client SDK? If yes, which one?

TypeScript

### Describe what the problem is?

Resuming ChainSync on Sanchonet slot 8877256 / block decf8e2c6ae737c23bf20e5dd3ed786fd83a5d2d84aec6e4eb899fd3065abee9 fails with `Websocket unexpectedly closed with code 1006`.

Same result with node `8.3.0-pre` and `8.4.0-pre`.

### What should be the expected behavior?

Chain Sync should work

### If applicable, what are the logs from the server around the occurence of the problem?

```
{"severity":"Error","timestamp":"2023-10-05T09:16:33.262867189Z","thread":"4420","message":{"WebSocket":{"exception":"DecoderFailure (ChainSync (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *))))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) ServerAgency TokNext TokCanAwait) (DeserialiseFailure 1231 \"An error occured while decoding Not a valid key:.\\nError: 0\")","tag":"WebSocketUnknownException"}},"version":"v6.0.0 (unknown revision)"}
{"severity":"Info","timestamp":"2023-10-05T09:16:33.263022411Z","thread":"4420","message":{"WebSocket":{"tag":"WebSocketConnectionEnded","userAgent":"User-Agent unknown"}},"version":"v6.0.0 (unknown revision)"}
```

**Comment by KtorZ** [comment]
It seems like the on-chain format has changed; most probably in the Conway era which is still in development. I am removing the `bug` label because this is slightly misleading. The Conway era isn't officially supported / released and breakage are expected in this area (as per the last release notes). 

I'll look into bumping internals deps of Ogmios to `8.4.0-pre` and release a `v6.0.0-rc3`.

**Comment by KtorZ** [comment]
(on its way)
