### ISSUE TITLE
Add support for 8.7.2

### ISSUE THREAD

**Issue by maestroi** [CardanoSolutions/ogmios#356]
### What is your idea? Provide a use case.

We would like to use ogmios on 8.7.2, since it's recommended tot test before 9 comes out

### Why is it a good idea?

It's good to have the version ready before 9.0.0 is there and make use new features.

### What is the current alternative and why is it not good enough?

There is no alternative to ogmios :D

**Comment by KtorZ** [comment]
Fixed in ae024914355b5defca5a66fb06c70e168aca8a3d.
