### ISSUE TITLE
SubmitTransactionFailureInternalLedgerTypeConversionError encountered

### ISSUE THREAD

**Issue by zliu41** [CardanoSolutions/ogmios#368]
### What Git revision / release tag are you using?

Unknown

### Do you use any client SDK? If yes, which one?

None

### Describe what the problem is?

Copied from https://github.com/IntersectMBO/plutus/issues/5770, reported by @jonathanfishbein1:

### Summary

Error: submit tx failed: ErrorSubmitTx.failed.(400)
failed:
aab3e076a3d3c29ada4cbac924937b5da7420fd1ea202caba0ce44dff88c1a47
Whoopsie, the ledger failed to upgrade an data-type from an earlier era into data of a newer era. If you ever run into this, please report the issue as you've likely discoverd a critical bug...

### Steps to reproduce the behavior

asdfasdf

### Actual Result

asfdasdf

### Expected Result

asdfasdf

### System info

NixOS
Brave

### What should be the expected behavior?

.

**Comment by KtorZ** [comment]
Please upgrade to the latest version, this issue was fixed in the latest release already 👍
