### ISSUE TITLE
HasTransaction returns false even when there's a matching tx in the mempool

### ISSUE THREAD

**Issue by szg251** [CardanoSolutions/ogmios#376]
### What Git revision / release tag are you using?

6.0.1

### Do you use any client SDK? If yes, which one?

None

### Describe what the problem is?

`hasTransaction` returns a `false` even though the transaction can be confirmed via `nextTransaction` calls.
A simple example:
```rs
            let _ = self.acquire_mempool().await?;
            dbg!(tx_hash);
            let has_tx = self.has_transaction(tx_hash).await?;
            dbg!(has_tx);
            let tx = self.next_transaction().await?;
            dbg!(tx);

```
The logs produced by `dbg`:
```
[src/utils/ogmios.rs:208] tx_hash = TransactionHash(
    82892b2eabd3e257a22733d8f6fd93c44edfd7171199292e6584f87c1c220362,
)
[src/utils/ogmios.rs:210] has_tx = false
[src/utils/ogmios.rs:212] tx = Object {
    "transaction": Object {
        "id": String("82892b2eabd3e257a22733d8f6fd93c44edfd7171199292e6584f87c1c220362"),
    },
}
```

### What should be the expected behavior?

HasTransaction returns true when tx is in mempool

**Comment by KtorZ** [comment]
I've been looking into this without success so far. I was originally suspecting an issue with the TypeScript client and possible coercion there. But no. The server is also working as expecting and the error comes from the node as far as I can tell. I've been tracing this back to the very messages sent to the node and, the node replies `False` even for transactions that are part of the mempool snapshot for some reason. 

I've inspected the current implementation and interestingly, the server-side implements the `hasTransaction` handler by using a side set of transaction id which is said to be "maintained in sync with the transaction in the mempool". I suppose that this statement might be invalid.

**Comment by KtorZ** [comment]
I found the issue in the consensus --> https://github.com/IntersectMBO/ouroboros-consensus/issues/1009

There's possibly a fix I can do in Ogmios while this gets fixed.
