### ISSUE TITLE
have problem run ogmios with newest cardano-node 

### ISSUE THREAD

**Issue by ironmask285** [CardanoSolutions/ogmios#387]
### What Git revision / release tag are you using?

6.3.0

### Do you use any client SDK? If yes, which one?

None

### Describe what the problem is?

I got issue with ogmios (6.3.0)  with  Cardano-node (8.11.0-pre) 
ogmios: DecoderFailure (LocalStateQuery HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))) Query (BlockQuery (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *))))))))))) ServerAgency TokQuerying BlockQuery (QueryHardFork GetInterpreter)) (DeserialiseFailure 13 "Size mismatch when decoding EraParams.\nExpected 3, but found 4.")

please help me 

### What should be the expected behavior?

work ogmios with cardano-node(8.11.0-pre)

**Comment by KtorZ** [comment]
Please refer to the README for compatibility with cardano node versions. 

This version isn't supporter (yet).

**Comment by NanuIjaz** [comment]
is there any plan to release ogmios for 8.11.0-pre node?

**Comment by KtorZ** [comment]
Eventually, yes.

**Comment by NanuIjaz** [comment]
is there any expected date?

**Comment by KtorZ** [comment]
No.
