### ISSUE TITLE
Ogmios 6.4.0 not support Cardano 8.11.0 (Sanchonet)

### ISSUE THREAD

**Issue by ironmask285** [CardanoSolutions/ogmios#392]
### What Git revision / release tag are you using?

6.4.0

### Do you use any client SDK? If yes, which one?

None

### Describe what the problem is?

{"severity":"Info","timestamp":"2024-06-14T03:47:40.340913304Z","thread":"5","message":{"Configuration":{"networkParameters":{"networkMagic":764824073,"slotsPerEpoch":21600,"systemStart":"2017-09-23T21:44:51Z"}}},"version":"v6.4.0 (4dbf1f34)"}
ogmios: HandshakeException "Unable to establish the connection with the cardano-node: it runs on a different network! Ogmios is configured for mainnet but the cardano-node is running on sanchonet. You probably want to use a different configuration."

### What should be the expected behavior?

Support Cardano node sanchonet

**Comment by KtorZ** [comment]
As indicated in the error message:

> Unable to establish the connection with the cardano-node: it runs on a different network! Ogmios is configured for mainnet but the cardano-node is running on sanchonet. You probably want to use a different configuration.

Please use the correct matching configuration. You can find configurations for various networks here: https://github.com/input-output-hk/cardano-configurations/tree/692010ed0f454bfbb566c06443227c79e2f4dbab/network or https://book.play.dev.cardano.org/environments.html
