### ISSUE TITLE
[INFO] ogmios version for cardano-node v9.0.0 (Chang hard fork)

### ISSUE THREAD

**Issue by saravadeanil** [CardanoSolutions/ogmios#402]
### What Git revision / release tag are you using?

6.2.0

### Do you use any client SDK? If yes, which one?

Go

### Describe what the problem is?

**Summary**

Hi, I am running cardano-node v8.9.0 with ogmios v6.2.0. Following is the list of versions I am using on preview/mainnet network.

```
cardano-node: v8.9.0
cardano-ogmios: v6.2.0
cardano-db-sync: v13.2.0.2
cardano-graphql-server: v8.1.0-preview/mainnet
cardano-graphql-background: v8.1.0-preview/mainnet
cardano-graphql-hasura: v8.1.0
cardano-postgres: v14.10-alpine
```

### What should be the expected behavior?

I would like to know the compatible/supported versions/releases for cardano-ogmios to run/upgrade to cardano node v9.0.0 Chang hard fork.

**Comment by KtorZ** [comment]
Hello, the new node version was released **TWO DAYS AGO**. There's already an open PR (#401) showing that work is being done towards the 9.0.0.

Chill out.
