### ISSUE TITLE
Incorrect documentation for `QueryLedgerStateStakePools`

### ISSUE THREAD

**Issue by SeungheonOh** [CardanoSolutions/ogmios#405]
### What Git revision / release tag are you using?

v6.5.0

### Do you use any client SDK? If yes, which one?

None

### Describe what the problem is?

Document states that for `QueryLedgerStateStakePools` endpoint parameter is required, which is not true since `queryLedgerState/stakePools` can be queried without any parameter, in which case, ogmios returns all stake pools in the node. 

### What should be the expected behavior?

Documentation should state that parameter for this endpoint is optional

**Comment by SeungheonOh** [comment]
https://github.com/CardanoSolutions/ogmios/blob/64100635bab88a1e2cad7ac9077c5a9573a1a31c/docs/static/api/v6.5/ogmios.json#L1424 

This is where it say parameter is required

**Comment by SeungheonOh** [comment]
Hmm, I see. If it's related to code generation, I wouldn't want to change it either. Perhaps, I should make a PR that adds a small note? There needs to be at least some indication of these behavior; I had to run it to figure out this behavior(of dumping all pool infos) exists.

**Comment by KtorZ** [comment]
> I  should make a PR that adds a small note

That's very welcome; In the state-query protocol part of the documentation, when presenting the queries, I think it makes sense.

**Comment by SeungheonOh** [comment]
PR Made!
