### ISSUE TITLE
Schema type definitions shouldn't be optional

### ISSUE THREAD

**Issue by MarcelKlammer** [CardanoSolutions/ogmios#41]
#### Describe what the problem is? 

The generated schema types, which are used to define expected types in code, shouldn't be optional as in

RequestNext?: ...

As those types are indeed defined right after the :

The ? 'confuses' auto completion and parsers, eg. result is not a property of RequestNext | undefined.

```

export interface Ogmios {
    RequestNext?: {
        type: "jsonwsp/request";
        version: "1.0";
        servicename: "ogmios";
        methodname: "RequestNext";
        args?: {};
        mirror?: {
            [k: string]: unknown;
        };
    };
...
}

```

#### What should be the expected behavior?

After removing all ? from the Ogmios types the parsers actually work.

**Comment by KtorZ** [comment]
@rhyslbw Any idea here?

**Comment by rhyslbw** [comment]
I think I'm missing some context here @MarcelKlammer. What do you mean by "the parsers actually work"? Can you paste a sample of your code so I can see this in context?

**Comment by rhyslbw** [comment]
The type definitions are derived from the [JSON-WSP schema](https://github.com/KtorZ/cardano-ogmios/blob/3fb1c139f5f25ae96d6a8884f538a572e31a4317/docs/static/ogmios.wsp.json#L7-L37), so either the interpretation of the schema needs to change in the generator, or it's a condition we must deal with. There are some potential changes with the JSON-WSP schema to explore, but have you tried using the [`@cardano-ogmios/client` package](https://github.com/KtorZ/cardano-ogmios/tree/master/clients/TypeScript/packages/client)? It should shield you from the particular issue you're raising with user-defined type guards along with existence checks within the client transformations.

**Comment by MarcelKlammer** [comment]
I prefer implementing against the socket api myself. Nothing against your code, but I don't like the "code flow".

maybe a 

```
, "required": [ "QueryResponse[stakeDistribution]", ... ] 
```
including all types right at the top would get rid of the trailing '?' ?

**Comment by rhyslbw** [comment]
No problem, that's why the schema is in a separate package :slightly_smiling_face: I'm also all for improving the generated output, as it will reduce the complexity in the `client` package too.

> including all types right at the top would get rid of the trailing '?' ?

Should be easy enough to test. Are you building from source, or using the package from the registry?
_The latter is out of date as we've not setup the workflow to publish releases yet_

https://github.com/KtorZ/cardano-ogmios/blob/3fb1c139f5f25ae96d6a8884f538a572e31a4317/clients/TypeScript/package.json#L19

**Comment by MarcelKlammer** [comment]
Yes, adding a required field with the type will result in non optional definitions.

**Comment by rhyslbw** [comment]
Reopening to use as task for TypeScript client update

**Comment by KtorZ** [comment]
@rhyslbw I am still unsure what you want to do with that one :sweat_smile: ? As far as I am concerned, the TypeScript type definitions are _okay_ and this issue can be closed? If there's something specific that needs doing, I'd suggest to open a new ticket about that specific item.

**Comment by rhyslbw** [comment]
Yes, pretty sure this is now obsolete @KtorZ
