### ISSUE TITLE
empty data structures are rejected by the ledger

### ISSUE THREAD

**Issue by mmahut** [CardanoSolutions/ogmios#410]
### What Git revision / release tag are you using?

master

### Do you use any client SDK? If yes, which one?

None

### Describe what the problem is?

As the ledger does not accept empty data structures anymore, Ogmios errors when it happens.

### What should be the expected behavior?

Ogmios handles this without a panic.

### If applicable, what are the logs from the server around the occurence of the problem?

```
{
  "severity": "Error",
  "timestamp": "2024-08-08T11:09:19.94077579Z",
  "thread": "68093",
  "message": {
    "WebSocket": {
      "exception": "DecoderErrorDeserialiseFailure \"body\" (DeserialiseFailure 185 \"TxBody: 'Required Signer Hashes' must be non-empty when supplied\")\nCallStack (from HasCallStack):\n  error, called at src/Relude/Debug.hs:296:11 in relude-1.2.1.0-B7TEg1zxmw6EFymYMoQ9yd:Relude.Debug\n  error, called at src/Ogmios/Data/EraTranslation.hs:105:27 in ogmios-6.5.0-Jcf6JDBoV4p5uZSxLuV6hB:Ogmios.Data.EraTranslation\n  unsafeFromRight, called at src/Ogmios/Data/EraTranslation.hs:95:26 in ogmios-6.5.0-Jcf6JDBoV4p5uZSxLuV6hB:Ogmios.Data.EraTranslation",
      "tag": "WebSocketUnknownException"
    }
  },
  "version": "v6.5.0 (unknown )"
}
```

**Comment by KtorZ** [comment]
@mmahut I suspect this happens only when evaluating transactions but not when submitting them, do you concur?

**Comment by vladimirvolek** [comment]
> @mmahut I suspect this happens only when evaluating transactions but not when submitting them, do you concur?

Correct!
