### ISSUE TITLE
Cross-platform testing of the TypeScript client

### ISSUE THREAD

**Issue by rhyslbw** [CardanoSolutions/ogmios#59]
#### Describe your idea, in simple words.
Extend the virtual environment matrix in the continuous integration workflow to include macOS and Windows.

#### Why is it a good idea?
We're only presently testing against Ubuntu, which leaves cross-platform support an unknown. 

#### Are you willing to work on it yourself?
Yes

**Comment by KtorZ** [comment]
Closing until further re-assessment.
