### ISSUE TITLE
Cross-platform testing of the server

### ISSUE THREAD

**Issue by rhyslbw** [CardanoSolutions/ogmios#60]
#### Describe your idea, in simple words.
Extend the virtual environment matrix in the continuous integration workflow to include macOS and Windows.

#### Why is it a good idea?
Given `cardano-node` has support for a "desktop" role, I think it's worth included cross-platform testing here.
https://github.com/input-output-hk/cardano-node/releases/tag/1.27.0

#### Are you willing to work on it yourself?
No

**Comment by KtorZ** [comment]
More than cross-platform testing, this is even about cross-platform support and to be frank, I am really not willing to support Windows unless there's a good use-case to do so. I can hear a voice already telling me about "running Ogmios as part of the Daedalus stack" and yes, that would be a use-case! Still.. windows :sob: ... I'll see maybe to prepare the ground and do things to work in that direction. Domain sockets are just painful to work with on Windows, and I hope WebSocket don't have the same pitfalls. 

On the other hand, MacOS should be rather trivial to add. Ogmios doesn't fiddle with the file-system so it should be quite straightforward in the end... maybe Windows is too after all.

**Comment by KtorZ** [comment]
Closing this one until there's a clear use-case about running Ogmios on Windows.
