### ISSUE TITLE
client/TypeScript: Fault response ignored

### ISSUE THREAD

**Issue by rhyslbw** [CardanoSolutions/ogmios#89]
#### What Git revision are you using? 
`a7bab073220caad8b98351515e3d68f5eb605383`
#### What operating system are you using, and which version?

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 
As reported in https://github.com/input-output-hk/cardano-graphql/issues/545
```
> await submitTx('abc')
# hangs
```

#### What should be the expected behavior?
A failure response

**Comment by rhyslbw** [comment]
There are two issues:
1. The server is not reflecting the request mirror value in a `Fault` response, which is used by the client to match handlers to requests.
_Line 30 discards the response_
https://github.com/CardanoSolutions/ogmios/blob/320c97aef8a823e6295412b16a8a3b29bea15dfe/clients/TypeScript/packages/client/src/StateQuery/Query.ts#L28-L37

2. The `Fault` response will fall-through to the 'UnexpectedResponseError`, so that should be improved.
https://github.com/CardanoSolutions/ogmios/blob/320c97aef8a823e6295412b16a8a3b29bea15dfe/clients/TypeScript/packages/client/src/TxSubmission/submitTx.ts#L156

**Comment by KtorZ** [comment]
Note: as per b94a8b2daba8fac55534083a3de8a96337d11339, the server now correctly returns the matching `mirror` / `reflection` on faults for invalid requests.

**Comment by KtorZ** [comment]
Fixed in #116
