### ISSUE TITLE
docs: odd comment in API reference

### ISSUE THREAD

**Issue by rhyslbw** [CardanoSolutions/ogmios#99]
#### What Git revision are you using? 
`eb2751d8a965303ba237ec438054c8975c1d8bc1`
#### What operating system are you using, and which version?
N/A

#### Describe what the problem is? 
![image](https://user-images.githubusercontent.com/303881/127968173-69c55e0b-2209-4113-8747-ece57a55bc34.png)

**Comment by KtorZ** [comment]
Well, the comment isn't wrong though :sweat_smile:  ... At an odd location surely.

**Comment by rhyslbw** [comment]
Odd in the context of user-facing docs :smile:

**Comment by rhyslbw** [comment]
https://ogmios.dev/api/modules/_cardano_ogmios_schema.html#Block
